/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autentikasi;

import com.mycompany.FantasyFittings.koneksiDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class LupaPW extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LupaPW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TombolRenew = new javax.swing.JToggleButton();
        Username = new javax.swing.JTextField();
        PasswordB = new javax.swing.JPasswordField();
        KPasswordB = new javax.swing.JPasswordField();
        LabelUsername = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        LabelKonfirmasiPassword = new javax.swing.JLabel();
        PesanLogin = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        TombolLogin = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TombolRenew.setBackground(new java.awt.Color(0, 153, 255));
        TombolRenew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolRenew.setForeground(new java.awt.Color(255, 255, 255));
        TombolRenew.setText("Renew");
        TombolRenew.setHideActionText(true);
        TombolRenew.setOpaque(true);
        TombolRenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolRenewActionPerformed(evt);
            }
        });

        LabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelUsername.setText("User");

        LabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelPassword.setText("Password Baru");

        LabelKonfirmasiPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelKonfirmasiPassword.setText("Konfirmasi Password");

        PesanLogin.setText("Sudah punya akun?");

        TombolLogin.setForeground(new java.awt.Color(0, 102, 204));
        TombolLogin.setText("Login");
        TombolLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TombolLoginMouseClicked(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setText("Lupa Password?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelUsername)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelPassword)
                            .addComponent(PasswordB, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelKonfirmasiPassword)
                            .addComponent(KPasswordB, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TombolRenew, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(PesanLogin)
                                .addGap(7, 7, 7)
                                .addComponent(TombolLogin))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Title)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelUsername)
                .addGap(4, 4, 4)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabelPassword)
                .addGap(4, 4, 4)
                .addComponent(PasswordB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabelKonfirmasiPassword)
                .addGap(4, 4, 4)
                .addComponent(KPasswordB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TombolRenew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PesanLogin)
                    .addComponent(TombolLogin))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void clearForm() {
        Username.setText("");
        PasswordB.setText("");
        KPasswordB.setText("");
    }
    
    private void TombolRenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolRenewActionPerformed
        try {
            // 01. Tangkap variabel inputan 
            String uname = Username.getText();
            String pw = new String(PasswordB.getPassword());
            String kpw = new String(KPasswordB.getPassword());

            // 01.1. Konfirmasi Inputan
            if (!pw.equals(kpw)) {
                JOptionPane.showMessageDialog(null, "Pastikan konfirmasi password sesuai");
                return;
            }

            // 02. Query SQL - INSERT
            String perintahUpdate_SQL = "UPDATE pengguna SET password = ? WHERE username = ?";

            // 03. Menghubungkan SQL - Java
            Connection penghubung = koneksiDB.konfigurasi_koneksiDB();
            if (penghubung == null) {
                JOptionPane.showMessageDialog(null, "Koneksi ke database gagal. Silakan cek konfigurasi database Anda.");
                return;
            }

            // 04. Membuat PreparedStatement
            PreparedStatement pernyataanSQL = penghubung.prepareStatement(perintahUpdate_SQL);
            pernyataanSQL.setString(1, pw);
            pernyataanSQL.setString(2, uname);

            // 05. Mengeksekusi perintah SQL
            int rowsUpdated = pernyataanSQL.executeUpdate();

            // 06. Validasi data SQL
            if (rowsUpdated > 0) {
                // Kondisi Berhasil
                JOptionPane.showMessageDialog(null, "Pembaruan Password Berhasil.");
                new Login().setVisible(true); //Meredirect ke object Login
                this.dispose(); // Menutup window login
            } else {
                // Kondisi Gagal 
                JOptionPane.showMessageDialog(null, "Gagal Memperbarui Password.");
                clearForm();
            }

            // Tutup pernyataanSQL dan penghubung
            pernyataanSQL.close();
            penghubung.close();

        } catch (SQLException e) {
            // 07. Exception()
            JOptionPane.showMessageDialog(null, "Registrasi Gagal \n" + e.getMessage());
        }
    }//GEN-LAST:event_TombolRenewActionPerformed

    private void TombolLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolLoginMouseClicked
        new Login().setVisible(true); //Meredirect ke object Register
        this.dispose();
    }//GEN-LAST:event_TombolLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaPW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPasswordField KPasswordB;
    private javax.swing.JLabel LabelKonfirmasiPassword;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JPasswordField PasswordB;
    private javax.swing.JLabel PesanLogin;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TombolLogin;
    private javax.swing.JToggleButton TombolRenew;
    private javax.swing.JTextField Username;
    // End of variables declaration//GEN-END:variables
}
